name: RiseCity
version: ${project.version}
main: rise.city.RiseCity
api-version: 1.17
depend: [PlaceholderAPI, Vault]
softdepend: [PlaceholderAPI, Vault]
commands:
  dc:
  tc:
  cench:
  ah:
  warp:
  battery: