name: RiseCity
version: ${project.version}
main: rise.city.RiseCity
api-version: 1.17
depend: [ Vault, PlaceholderAPI, ProtocolLib ]
softdepend: [ Vault, PlaceholderAPI, ProtocolLib ]
authors: [ tcfplayzzzzzzzzzz ]
website: spmc.ml
